### PR TITLE
Hides failure message on password recovery

### PR DESCRIPTION
**Pull request by bricesanchez**
* Mitigate brute force attacks by giving no clue on existing accounts
* Refactor Refinery::Authentication::Devise::PasswordsController
* Fix offences with Rubocop

### CODE REVIEW

**Comment by bricesanchez** [comment]
@parndt i don't see codeclimate on this repo? Could you check why it's not activated on all the organization?

**Comment by parndt** [comment]
It's definitely configured for this repo

**Comment by bricesanchez** [comment]
> It's definitely configured for this repo

It's weird, i don't see it in the timeline actions with Travis CI.

**Comment by parndt** [comment]
It is weird, indeed.

**Comment by bricesanchez** [comment]
@parndt Could you review this PR please?

**Comment by parndt** [comment]
@bricesanchez yeah, can you please add screenshots showing how you expect this to function now?

**Comment by bricesanchez** [comment]
Yes.

Before it could helps a hacker to find which account is used as refinery Admin
refinery login clue

Now it give no clue, it always returns that an email has been send even if it does not send an email if the account does not exist

refinery login no clue

**Comment by parndt** [comment]
Thanks for doing it @bricesanchez :+1:

**Pull request merged**
